name: 24/7 Minecraft Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *' # Har 15 minute baad trigger karega
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install
        run: |
          npm install mineflayer
          pip install javascript

      - name: Run Bot
        run: python bot.py
        timeout-minutes: 350 # Takreeban 6 ghante
